# Generated by Django 5.0.6 on 2024-05-31 19:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of birth'),
            preserve_default=False,
        ),
    ]
