# Generated by Django 5.0.6 on 2024-05-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_category_category_name_alter_forum_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='picture',
            field=models.ImageField(blank=True, default='Other.jpg', upload_to='Forum_pic/'),
        ),
    ]
