# Generated by Django 5.0.6 on 2024-05-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_forum_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='picture',
            field=models.ImageField(blank=True, default='apod.jpg', upload_to='Forum_pic/'),
        ),
    ]
