# Generated by Django 5.0.6 on 2024-05-29 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_forum_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='published',
        ),
    ]
